services:
  haos:
    image: ghcr.io/podmania/home-assistant:latest
    # podman:
    userns_mode: "keep-id"
    # docker:
    # user: ${id -u}:${id -g}
    container_name: home-assistant
    devices:
      - /dev/kvm
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
    environment:
      - CPU_CORES=2
      - RAM_SIZE=4096
      - FORWARD_PORT=8123
    restart: always
